### ISSUE TITLE
Change id/1 by  duplication_conditions/1 to sumo_rest_doc

### ISSUE THREAD

**Issue by elbrujohalcon** [inaka/sumo_rest#53]
The callback function `id/1` in `sumo_rest_doc` requests the implementor to retrieve a unique field to determine if the doc is duplicated.
We need to change that function to `duplication_conditions/1` and allow the implementor to provide a list of conditions for sumo_rest to use `sumo:find_one/2` to find the duplicate.

Remember to:
- [ ] Change the callback on `sumo_rest_doc`
- [ ] Update the docs
- [ ] Bump minor version (because of backwards compatibility break)
- [ ] Be happy! 🎉

**Comment by ferigis** [comment]
The version bump point will be done on a separate ticket #55
